/**
 * @file themes.ts
 * This file defines the preset layouts and themes for the SVG game card generator.
 * Each layout can have multiple themes, which are pre-configured sets of styles
 * that users can select from the control panel.
 */
import type { Layout } from './types';

/**
 * @const {Layout[]} layouts
 * @description An array of `Layout` objects that define the structure of the theme library.
 * It is organized into categories (like 'Vertical Card', 'Horizontal Banner', and 'Imported Themes'),
 * each containing a list of predefined `Theme` objects. These themes serve as starting points
 * for users and are displayed in the "Templates & Presets" tab. The 'imported' layout is
 * initially empty and is populated with themes imported by the user.
 */
export const layouts: Layout[] = [
  {
    id: 'vertical',
    name: 'Vertical Card',
    themes: [
      {
        name: "Space Explorer",
        layoutId: 'vertical',
        config: {
          title: "Space Explorer's Pack",
          price: 4.99,
          priceCurrencySymbol: "$",
          priceCurrencySymbolOffsetX: 5,
          useCustomCurrencyIcon: false,
          customCurrencyIconSize: 18,
          customCurrencyIconOffsetX: 0,
          customCurrencyIconOffsetY: 0,
          buttonText: "BUY NOW",
          cardColor: "#FFFFFF",
          buttonColor: "#6D28D9", // Fallback color
          buttonTextColor: "#FFFFFF",
          textColor: "#2C3E50",
          priceColor: "#A0AEC0",
          priceCurrencyColor: "#A0AEC0",
          matchPriceColor: true,
          frameColor: "#3A4D8F",
          cardStrokeColor: "#E2E8F0",
          cardStrokeWidth: 3,
          cardStrokeEnabled: true,
          titleFontFamily: "'Poppins', sans-serif",
          priceFontFamily: "'Poppins', sans-serif",
          buttonFontFamily: "'Poppins', sans-serif",
          titleBold: true,
          priceBold: false,
          buttonBold: true,
          titleFontSize: 19,
          priceFontSize: 16,
          buttonFontSize: 16,
          cardCornerRadius: 24,
          buttonGradientEnabled: true,
          buttonGradientColorStart: "#5B21B6",
          buttonGradientColorEnd: "#1E40AF",
          buttonGradientAngle: 120,
          buttonWidth: 180,
          buttonHeight: 50,
          cardHeight: 400,
          cardWidth: 300,
          titleOffsetX: 0,
          titleOffsetY: 0,
          priceOffsetX: 0,
          priceOffsetY: 6,
          buttonTextOffsetX: 0,
          buttonTextOffsetY: 0,
          imageOffsetX: 0,
          imageOffsetY: 0,
          imageScale: 1,
        }
      },
      {
        name: "Ocean's Bounty",
        layoutId: 'vertical',
        config: {
          title: "Ocean's Bounty",
          price: 5.00,
          priceCurrencySymbol: "$",
          priceCurrencySymbolOffsetX: 5,
          useCustomCurrencyIcon: false,
          customCurrencyIconSize: 22,
          customCurrencyIconOffsetX: 0,
          customCurrencyIconOffsetY: 0,
          buttonText: "BUY",
          cardColor: "#6E9998",
          buttonColor: "#E58672",
          buttonTextColor: "#FFFFFF",
          textColor: "#2C3E50",
          priceColor: "#FFFFFF",
          priceCurrencyColor: "#FFFFFF",
          matchPriceColor: true,
          frameColor: "#FFFFFF",
          cardStrokeColor: "#4a5568",
          cardStrokeWidth: 4,
          cardStrokeEnabled: true,
          titleFontFamily: "'Nunito', sans-serif",
          priceFontFamily: "'Nunito', sans-serif",
          buttonFontFamily: "'Nunito', sans-serif",
          titleBold: true,
          priceBold: false,
          buttonBold: true,
          titleFontSize: 28,
          priceFontSize: 20,
          buttonFontSize: 18,
          cardCornerRadius: 35,
          buttonGradientEnabled: false,
          buttonGradientColorStart: '#4facfe',
          buttonGradientColorEnd: '#00f2fe',
          buttonGradientAngle: 90,
          buttonWidth: 200,
          buttonHeight: 55,
          cardWidth: 340,
          cardHeight: 470,
          titleOffsetX: 0,
          titleOffsetY: 0,
          priceOffsetX: 0,
          priceOffsetY: 6,
          buttonTextOffsetX: 0,
          buttonTextOffsetY: 0,
          imageOffsetX: 0,
          imageOffsetY: 0,
          imageScale: 1,
        }
      },
      {
        name: "Mare Skins",
        layoutId: 'vertical',
        config: {
          title: "Mare Skins",
          price: 2.00,
          priceCurrencySymbol: "$",
          priceCurrencySymbolOffsetX: 5,
          useCustomCurrencyIcon: false,
          customCurrencyIconSize: 22,
          customCurrencyIconOffsetX: 0,
          customCurrencyIconOffsetY: 0,
          buttonText: "BUY",
          cardColor: "#FFFFFF",
          buttonColor: "#EDEDED",
          buttonTextColor: "#757575",
          textColor: "#333333",
          priceColor: "#BBBBBB",
          priceCurrencyColor: "#BBBBBB",
          matchPriceColor: true,
          frameColor: "#FFFFFF",
          cardStrokeColor: "#EAEAEA",
          cardStrokeWidth: 2,
          cardStrokeEnabled: true,
          titleFontFamily: "'Poppins', sans-serif",
          priceFontFamily: "'Poppins', sans-serif",
          buttonFontFamily: "'Poppins', sans-serif",
          titleBold: true,
          priceBold: false,
          buttonBold: true,
          titleFontSize: 28,
          priceFontSize: 20,
          buttonFontSize: 18,
          cardCornerRadius: 35,
          buttonGradientEnabled: false,
          buttonGradientColorStart: '#f6f6f6',
          buttonGradientColorEnd: '#e0e0e0',
          buttonGradientAngle: 90,
          buttonWidth: 200,
          buttonHeight: 55,
          cardWidth: 340,
          cardHeight: 470,
          titleOffsetX: 0,
          titleOffsetY: 0,
          priceOffsetX: 0,
          priceOffsetY: 6,
          buttonTextOffsetX: 0,
          buttonTextOffsetY: 0,
          imageOffsetX: 0,
          imageOffsetY: 0,
          imageScale: 1,
        }
      },
      {
        name: "Mythical Mounts",
        layoutId: 'vertical',
        config: {
          title: "Mythical Mounts",
          price: 15.00,
          priceCurrencySymbol: "$",
          priceCurrencySymbolOffsetX: 5,
          useCustomCurrencyIcon: false,
          customCurrencyIconSize: 22,
          customCurrencyIconOffsetX: 0,
          customCurrencyIconOffsetY: 0,
          buttonText: "PURCHASE",
          cardColor: "#EDF5FF",
          buttonColor: "#1D79F6",
          buttonTextColor: "#FFFFFF",
          textColor: "#2D3748",
          priceColor: "#1D79F6",
          priceCurrencyColor: "#1D79F6",
          matchPriceColor: true,
          frameColor: "#1D79F6",
          cardStrokeColor: "#000000",
          cardStrokeWidth: 4,
          cardStrokeEnabled: true,
          titleFontFamily: "'Poppins', sans-serif",
          priceFontFamily: "'Poppins', sans-serif",
          buttonFontFamily: "'Poppins', sans-serif",
          titleBold: true,
          priceBold: false,
          buttonBold: true,
          titleFontSize: 28,
          priceFontSize: 20,
          buttonFontSize: 18,
          cardCornerRadius: 35,
          buttonGradientEnabled: false,
          buttonGradientColorStart: '#2989f8',
          buttonGradientColorEnd: '#135cbf',
          buttonGradientAngle: 90,
          buttonWidth: 200,
          buttonHeight: 55,
          cardWidth: 340,
          cardHeight: 470,
          titleOffsetX: 0,
          titleOffsetY: 0,
          priceOffsetX: 0,
          priceOffsetY: 6,
          buttonTextOffsetX: 0,
          buttonTextOffsetY: 0,
          imageOffsetX: 0,
          imageOffsetY: 0,
          imageScale: 1,
        }
      }
    ]
  },
  {
    id: 'horizontal',
    name: 'Horizontal Banner',
    themes: [
      {
        name: "Mana Crystal",
        layoutId: 'horizontal',
        config: {
          title: "Mana Crystal Pack",
          price: 5.99,
          priceCurrencySymbol: "$",
          priceCurrencySymbolOffsetX: 5,
          useCustomCurrencyIcon: false,
          customCurrencyIconSize: 18,
          customCurrencyIconOffsetX: 0,
          customCurrencyIconOffsetY: 0,
          buttonText: "BUY",
          cardColor: "#FFFFFF",
          buttonColor: "#EDEDED",
          buttonTextColor: "#757575",
          textColor: "#333333",
          priceColor: "#999999",
          priceCurrencyColor: "#999999",
          matchPriceColor: true,
          frameColor: "#FDFDFD",
          cardStrokeColor: "#EAEAEA",
          cardStrokeWidth: 2,
          cardStrokeEnabled: true,
          titleFontFamily: "'Inter', sans-serif",
          priceFontFamily: "'Inter', sans-serif",
          buttonFontFamily: "'Inter', sans-serif",
          titleBold: true,
          priceBold: false,
          buttonBold: true,
          titleFontSize: 22,
          priceFontSize: 16,
          buttonFontSize: 14,
          cardCornerRadius: 18,
          buttonGradientEnabled: false,
          buttonGradientColorStart: '#f6f6f6',
          buttonGradientColorEnd: '#e0e0e0',
          buttonGradientAngle: 90,
          buttonWidth: 90,
          buttonHeight: 40,
          cardWidth: 500,
          cardHeight: 120,
          titleOffsetX: 0,
          titleOffsetY: 0,
          priceOffsetX: 0,
          priceOffsetY: 6,
          buttonTextOffsetX: 0,
          buttonTextOffsetY: 0,
          imageOffsetX: 0,
          imageOffsetY: 0,
          imageScale: 1,
        }
      },
    ]
  },
  {
    id: 'imported',
    name: 'Imported Themes',
    themes: []
  }
];